project_id = "vawcbbnnjhuitqxabygs"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]

[functions.request-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.modempay-webhook]
verify_jwt = false

[functions.complete-vendor-invite]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.purgo-filter]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.create-short-url]
verify_jwt = false

[functions.generate-ticket-qr]
verify_jwt = false

[functions.notify-new-application]
verify_jwt = false