// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vawcbbnnjhuitqxabygs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhd2NiYm5uamh1aXRxeGFieWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNDU2OTAsImV4cCI6MjA4OTYyMTY5MH0._chQ7BjdZe5IPQSFZh9o-nj3HKQaL-6gk7ljctYgobQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});